In [1]:
import numpy as np
horsepower=[130,165,150,150,140]
horsepower_arr=np.array(horsepower)
x=np.where(horsepower_arr>=150)
print(x)
horsepower_arr[x]

(array([1, 2, 3], dtype=int64),)


array([165, 150, 150])

In [2]:
hosrsepower=[130,165,150,150,140]
horsepower_arr=np.array(horsepower)
x=horsepower_arr>135
print(x.dtype)
newarr=horsepower_arr[x]
print(x)
print(newarr)


bool
[False  True  True  True  True]
[165 150 150 140]
