In [5]:
import numpy as np
horsepower_arr=[130,165,150,150,140]
print('original array:',horsepower_arr)
print('sorted array:',np.sort(horsepower_arr))
print('original array after sorting:',horsepower_arr)
sortedarray=np.sort(horsepower_arr)
print(sortedarray)

      

original array: [130, 165, 150, 150, 140]
sorted array: [130 140 150 150 165]
original array after sorting: [130, 165, 150, 150, 140]
[130 140 150 150 165]


In [7]:
import numpy as np
horsepower_arr=[130,165,150,150,140]
horsepower_arr=np.array(horsepower)
np.sort(horsepower_arr)
print(horsepower_arr)
horsepower_arr.sort()
print(horsepower_arr)

[130 165 150 150 140]
[130 140 150 150 165]


In [8]:
horsepower_arr=[130,165,150,150,140]
horsepower_arr=np.array(horsepower)
print('original array:',horsepower_arr)
horsepower_arr.sort()
print('original array after sorting:',horsepower_arr)

original array: [130 165 150 150 140]
original array after sorting: [130 140 150 150 165]
