In [5]:
import numpy as np
car_attributes=[[18,15,18,16,17],[130,165,150,150,140],[307,350,318,304,302]]
car_attributes_arr=np.array(car_attributes)
car_attributes_arr

array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [4]:
car_attributes_arr.shape

(3, 5)

In [6]:
car_attributes_arr.dtype


dtype('int32')

In [7]:
import numpy as np
car_attributes=[[18,15,18,16,17],[130,165,150,150,140],[307,350,318,304,302]]
car_attributes_arr=np.array(car_attributes,dtype="float")
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64
